server:
  port: 8080
  shutdown: graceful # tell the server to wait for executing requests to finish before shutdown
  forward-headers-strategy: "NATIVE"
  tomcat:
    remoteip:
      protocol-header: "x-forwarded-proto"
      protocol-header-https-value: "https"
      remote-ip-header: "x-forwarded-for"
    #  internal-proxies: ".*" # trust everything we don't know ip address the k8s worker nodes are using if a service forwards the request

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true # on K8s this is turned on by default
      group:
        readiness:
          include: "readinessState,example"
  endpoints:
    web:
      exposure:
        include: "*"

