apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: boot-net-debugger
  name: boot-net-debugger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boot-net-debugger
  strategy: {}
  template:
    metadata:
      labels:
        app: boot-net-debugger
    spec:
      containers:
        - image: "asaikali/boot-net-debugger:latest"
          imagePullPolicy: Always
          name: boot-net-debugger
          resources: {}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
