apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-boot
  name: k8s-boot
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: k8s-boot

