apiVersion: v1
kind: Service
metadata:
  labels:
    app: boot-net-debugger
  name: boot-net-debugger
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: boot-net-debugger

